name: Create Test Reports
on:
  push:
    branches: [main]
jobs:
  report:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Test Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint coverage anybadge bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Static Analysis
        run: python static_analysis.py
      - name: Run Bandit
        run: bandit -r bran -f json -o bandit.json
      - name: Upload PyLint Badge
        uses: actions/upload-artifact@v2
        with:
          name: pylint.svg
          path: ${{ github.workspace }}/pylint.svg
      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v2
        with:
          name: coverage.svg
          path: ${{ github.workspace }}/coverage.svg